package internal

type fitsKeywords struct {
	blank     string
	AUTHOR    string
	BITPIX    int32
	BLANK     int32
	BLOCKED   bool
	BSCALE    float32
	BUNIT     string
	BZERO     float32
	CDELTn    float32
	COMMENT   string
	CROTAn    float32
	CRPIXn    float32
	CRVALn    float32
	CTYPEn    string
	DATAMAX   float32
	DATAMIN   float32
	DATE      string
	DATE_OBS  string
	END       string
	EPOCH     float32
	EQUINOX   float32
	EXTEND    bool
	EXTLEVEL  int32
	EXTNAME   string
	EXTVER    int32
	GCOUNT    int32
	GROUPS    bool
	HISTORY   string
	INSTRUME  string
	NAXIS     int32
	NAXISn    int32
	OBJECT    string
	OBSERVER  string
	ORIGIN    string
	PCOUNT    int32
	PSCALn    float32
	PTYPEn    string
	PZEROn    float32
	REFERENC  string
	SIMPLE    bool
	TBCOLn    int32
	TDIMn     string
	TDISPn    string
	TELESCOP  string
	TFIELDS   int32
	TFORMn    string
	THEAP     int32
	TNULLnINT int32
	TNULLnSTR string
	TSCALn    float32
	TTYPEn    string
	TUNITn    string
	TZEROn    float32
	XTENSION  string
}
